"use client";
import {FormEvent,useState} from "react";
import {isSupabaseConfigured,supabase} from "../../../infrastructure/supabase/client";
export default function AuthPanel({onContinueDemo,onBack}:{onContinueDemo:()=>void;onBack?:()=>void}){
  const[email,setEmail]=useState(""),[password,setPassword]=useState(""),[mode,setMode]=useState<"signin"|"signup">("signin"),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
  const submit=async(e:FormEvent)=>{e.preventDefault();if(!isSupabaseConfigured)return setMessage("Supabase 环境变量尚未配置。");setBusy(true);setMessage("");const result=mode==="signup"?await supabase.auth.signUp({email,password,options:{data:{display_name:email.split("@")[0]}}}):await supabase.auth.signInWithPassword({email,password});setBusy(false);setMessage(result.error?.message??(mode==="signup"?"注册成功，请检查邮箱确认链接。":"正在进入训练舱…"))};
  const magicLink=async()=>{if(!email)return setMessage("请先填写邮箱。");setBusy(true);const{error}=await supabase.auth.signInWithOtp({email,options:{emailRedirectTo:location.origin}});setBusy(false);setMessage(error?.message??"登录链接已经发到邮箱。");};
  return <main className="authShell"><div className="authOrbit" aria-hidden="true"><i/><i/><i/></div>{onBack&&<button className="authBack" onClick={onBack}>← 返回首页</button>}<section className="authIntro"><p className="kicker">FORMA / PERSONAL ORBIT</p><h1>让每一次训练，<br/><strong>回应今天的你。</strong></h1><p>睡眠、疲劳、时间与器材共同决定今天的计划。登录后在所有设备同步训练轨迹。</p><div className="authSignals"><span><b>01</b>每日准备度</span><span><b>02</b>自适应训练</span><span><b>03</b>私密云端记录</span></div></section><form className="authCard" onSubmit={submit}><div><small>SECURE ACCESS</small><h2>{mode==="signin"?"返回你的轨道":"建立训练档案"}</h2></div><label>邮箱<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label><label>密码<input type="password" required minLength={6} value={password} onChange={e=>setPassword(e.target.value)} placeholder="至少 6 位"/></label>{message&&<p className="authMessage">{message}</p>}<button className="authPrimary" disabled={busy}>{busy?"连接中…":mode==="signin"?"登录训练舱 →":"创建账号 →"}</button><button type="button" className="authMagic" onClick={magicLink} disabled={busy}>发送免密码登录链接</button><button type="button" className="authSwitch" onClick={()=>setMode(mode==="signin"?"signup":"signin")}>{mode==="signin"?"没有账号？立即注册":"已有账号？返回登录"}</button><button type="button" className="authDemo" onClick={onContinueDemo}>先体验演示模式</button></form></main>;
}
