"use client";
import {useState} from "react";
import {calculateReadiness,ReadinessRecommendation} from "../domain/adaptive-training";
export default function ReadinessCard({onSave}:{onSave:(input:{sleepHours:number;energy:number;soreness:number;mood:number;availableMinutes:number;soreAreas:string[]},result:ReadinessRecommendation)=>Promise<void>|void}){
  const[expanded,setExpanded]=useState(false),[sleepHours,setSleepHours]=useState(7.5),[energy,setEnergy]=useState(4),[soreness,setSoreness]=useState(2),[mood,setMood]=useState(4),[availableMinutes,setAvailableMinutes]=useState(30),[soreAreas,setSoreAreas]=useState<string[]>([]),[saved,setSaved]=useState(false);
  const input={sleepHours,energy,soreness,mood,availableMinutes,soreAreas},result=calculateReadiness(input);
  const save=async()=>{await onSave(input,result);setSaved(true);setTimeout(()=>setSaved(false),1800)};
  return <section className={`readinessCard ${expanded?"expanded":""}`}><button className="readinessSummary" onClick={()=>setExpanded(!expanded)} aria-expanded={expanded}><span className="readinessGauge" style={{"--readiness":`${result.score*3.6}deg`} as React.CSSProperties}><b>{result.score}</b><small>READY</small></span><span><small>DAILY SIGNAL / 自适应训练</small><strong>{result.title}</strong><i>{result.detail}</i></span><em>{expanded?"收起":"校准今日状态"} ↗</em></button>{expanded&&<div className="readinessForm"><label>睡眠 <b>{sleepHours}h</b><input type="range" min="3" max="10" step="0.5" value={sleepHours} onChange={e=>setSleepHours(Number(e.target.value))}/></label><label>能量 <b>{energy}/5</b><input type="range" min="1" max="5" value={energy} onChange={e=>setEnergy(Number(e.target.value))}/></label><label>酸痛 <b>{soreness}/5</b><input type="range" min="1" max="5" value={soreness} onChange={e=>setSoreness(Number(e.target.value))}/></label><label>心情 <b>{mood}/5</b><input type="range" min="1" max="5" value={mood} onChange={e=>setMood(Number(e.target.value))}/></label><div className="timePick"><small>今天可用时间</small>{[10,20,30,45].map(n=><button className={availableMinutes===n?"active":""} onClick={()=>setAvailableMinutes(n)} key={n}>{n} 分钟</button>)}</div><div className="sorePick"><small>需要避开的部位</small>{["肩","腰","膝","脚踝"].map(area=><button className={soreAreas.includes(area)?"active":""} onClick={()=>setSoreAreas(v=>v.includes(area)?v.filter(x=>x!==area):[...v,area])} key={area}>{area}</button>)}</div><div className="readinessResult"><span><small>推荐强度</small><b>{result.intensity}</b></span><p>{result.note}</p><button onClick={save}>{saved?"已同步 ✓":"采用今日建议 →"}</button></div></div>}</section>;
}
